services:
  - type: web
    name: luana-bot
    env: node
    plan: free
    buildCommand: npm install && npm rebuild better-sqlite3 && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: PORT
        value: 3000
